name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm install

      - name: Lint JS
        run: npx eslint .

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Lint JS with Enhanced Rules
        run: npx eslint --config eslint.enhanced.config.js ${{ steps.changed-files.outputs.added_files }}
